### ISSUE TITLE
Support for 'echo' => false argument in fallback

### ISSUE THREAD

**Issue by toddlevy** [wp-bootstrap/wp-bootstrap-navwalker#249]
Currently, if there is **no menu set**, and you call ```wp_nav_menu``` with ```'echo' => false``` argument, the ```fallback``` function will output content into <head>.

Additionally, this output should get escaped before it's echoed / returned.

Here's my little patch for line 203...

**BEFORE**
```
echo $fb_output;
```

**AFTER**
```
// escape the output
$fb_output_safe = wp_kses_post( $fb_output );

// if echo, echo, otherwise return
if ( $args['echo'] ):
  echo $fb_output_safe;
else:
    return $fb_output_safe;
endif;      
```

**Comment by toddlevy** [comment]
Actually, I think this may be preferred approach, with late escaping...

```
// escape the output
// if echo, echo, otherwise return
if ( $args['echo'] ):
  echo wp_kses_post( $fb_output );
else:
    return $fb_output;
endif;   
```

**Comment by bhubbard** [comment]
@toddlevy Can you test your code with the new version we just released 2.0.5? It may no longer be needed.

**Comment by toddlevy** [comment]
Just took a glance at the fallback function here...
https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/master/wp-bootstrap-navwalker.php
... and I still don't see any check for the 'echo' argument, so I'm not sure how the issue could be resolved.

Moreover, I still don't see any escaping of the fallback output, and the way the new code has a ton of echo statements instead of a singular one at the end makes doing so more cumbersome.

Aside: glad to see that "extract" got killed :)

**Comment by bhubbard** [comment]
Yeah so the new code doesn't use ```$fb_output``` at all, but does esc calls in multiple places, feel free to review and submit a pull request.

**Comment by toddlevy** [comment]
First time using github / github desktop so I hope I've done this correctly.

Pull request is here...
https://github.com/wp-bootstrap/wp-bootstrap-navwalker/pull/268
